apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres-db
          image: 'postgres:latest'
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: employeemanagement
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: docker
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      volumes:
        - name: postgres-data
          emptyDir: {}